# ===================================================================
# This NSIS Script has been generated by SFX Tool
# Version 1.01
# Written by MuldeR (MuldeR2@GMX.de)
# Visit httpmulder.at.gg for further information!
#
# This application is based on NSIS v2.11 by Nullsoft
# ===================================================================



# -------------------------------------------------------------------
# Set Working Directory
# -------------------------------------------------------------------

!cd CProgram Files (x86)MuldeR's FreewareSFX Tool v1.01Resources


# -------------------------------------------------------------------
# Define Variables
# -------------------------------------------------------------------

var STARTMENU_FOLDER


# -------------------------------------------------------------------
# Choosing Compressor
# -------------------------------------------------------------------

SetCompressor LZMA
SetCompressorDictSize 32
SetCompress Auto
SetDatablockOptimize On


# -------------------------------------------------------------------
# SFX Definitions
# -------------------------------------------------------------------

!define SFX_AppID {41BE723A-DD1C-4664-8E71-EB731FBBAFB6}; a unique ID for your SFX (It's real GUID)
!define SFX_BaseDir CProgram Files (x86)MuldeR's FreewareSFX Tool v1.01; the SFX Tool install folder - do NOT edit!
!define SFX_Title Universal Reloader 0.1; the installer title
!define SFX_InstallDir $PROGRAMFILESUniversalReloader; the default destination directory
!define SFX_OutFile FsvnIrisSoftUniversalReloaderUniversalReloader_0.1_install.exe; the file to save the installer EXE to
!define SFX_IconFile WinXP; the installer icon
!define SFX_HeaderImage Win; the herader image
!define SFX_WizardImage Nullsoft; the wizard image


# -------------------------------------------------------------------
# Reserve Files
# -------------------------------------------------------------------

ReserveFile PluginsInstallOptions.dll
ReserveFile PluginsLangDLL.dll
ReserveFile PluginsStartMenu.dll
ReserveFile PluginsUserInfo.dll
ReserveFile PluginsBGImage.dll
ReserveFile ContribGraphicsWizard${SFX_WizardImage}.bmp
ReserveFile ContribGraphicsHeader${SFX_HeaderImage}.bmp
ReserveFile ContribGraphicsHeader${SFX_HeaderImage}-R.bmp
ReserveFile ContribModern UIioSpecial.ini


# -------------------------------------------------------------------
# General Settings
# -------------------------------------------------------------------

XPStyle On
CRCCheck Force
ShowInstDetails Show
ShowUninstDetails Show
BrandingText SFX Tool v1.01, NSIS v2.11
Name ${SFX_Title}
OutFile ${SFX_OutFile}
InstallDir ${SFX_InstallDir}
InstallDirRegKey HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID} InstallDirectory


# -------------------------------------------------------------------
# Modern Interface Settings
# -------------------------------------------------------------------

!include MUI.nsh

!define MUI_ICON ContribGraphicsIcons${SFX_IconFile}-Install.ico
!define MUI_WELCOMEFINISHPAGE_BITMAP ContribGraphicsWizard${SFX_WizardImage}.bmp
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP ContribGraphicsHeader${SFX_HeaderImage}.bmp
!define MUI_HEADERIMAGE_BITMAP_RTL ContribGraphicsHeader${SFX_HeaderImage}-R.bmp
!define MUI_ABORTWARNING
!define MUI_WELCOMEPAGE_TITLE_3LINES
!define MUI_FINISHPAGE_TITLE_3LINES
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_LANGDLL_REGISTRY_ROOT HKLM
!define MUI_LANGDLL_REGISTRY_KEY SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID}
!define MUI_LANGDLL_REGISTRY_VALUENAME InstallLanguage
!define MUI_LANGDLL_ALWAYSSHOW
!define MUI_FINISHPAGE_RUN $INSTDIRUniversalReloader.exe
!define MUI_FINISHPAGE_RUN_PARAMETERS 
!define MUI_FINISHPAGE_SHOWREADME $INSTDIRGPL-3.0 fr.txt
!define MUI_FINISHPAGE_LINK httpwww.irissoft.fr.nf
!define MUI_FINISHPAGE_LINK_LOCATION httpwww.irissoft.fr.nf
!define MUI_STARTMENUPAGE_REGISTRY_ROOT HKLM
!define MUI_STARTMENUPAGE_REGISTRY_KEY SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID}
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME StartmenuFolder
!define MUI_LICENSEPAGE_RADIOBUTTONS
!define MUI_UNICON ContribGraphicsIcons${SFX_IconFile}-Uninstall.ico
!define MUI_UNWELCOMEFINISHPAGE_BITMAP ContribGraphicsWizard${SFX_WizardImage}.bmp
!define MUI_UNFINISHPAGE_NOAUTOCLOSE
!define MUI_UNABORTWARNING
!define MUI_CUSTOMFUNCTION_UNGUIINIT un.InitializeGUI
!define MUI_CUSTOMFUNCTION_GUIINIT InitializeGUI

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE cuserslucappdatalocaltemp~014d7f8.txt
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_STARTMENU Application $STARTMENU_FOLDER
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH


# -------------------------------------------------------------------
# Multi-Language Support
# -------------------------------------------------------------------

!insertmacro MUI_LANGUAGE English
!insertmacro MUI_LANGUAGE French
!insertmacro MUI_LANGUAGE Spanish
!insertmacro MUI_LANGUAGE Italian


# -------------------------------------------------------------------
# Install Files Section
# -------------------------------------------------------------------

Section
  SetOutPath $INSTDIR
  File r FsvnIrisSoftUniversalReloaderGPL-3.0 fr.txt
  File r FsvnIrisSoftUniversalReloaderGPL-3.0.fr.html
  File r FsvnIrisSoftUniversalReloaderGPL-3.0.txt
  File r FsvnIrisSoftUniversalReloaderUniversalReloader.exe
  File r FsvnIrisSoftUniversalReloaderUniversalReloader.ini
SectionEnd


# -------------------------------------------------------------------
# Create Uninstaller Section
# -------------------------------------------------------------------

Section
  SetOutPath $INSTDIR
  WriteUninstaller $INSTDIRUninstall.exe
  WriteRegStr HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID} DisplayName ${SFX_Title}
  WriteRegStr HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID} DisplayIcon $$INSTDIRUninstall.exe$
  WriteRegStr HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID} UninstallString $$INSTDIRUninstall.exe$
  WriteRegDWORD HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID} NoModify 1
  WriteRegDWORD HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID} NoRepair 1
SectionEnd


# -------------------------------------------------------------------
# Startmenu Section
# -------------------------------------------------------------------

Section
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application

  SetShellVarContext all
  CreateDirectory $SMPROGRAMS$STARTMENU_FOLDER
  CreateShortCut $SMPROGRAMS$STARTMENU_FOLDERLire la lissence gpl 3 en anglais.lnk $INSTDIRGPL-3.0.txt
  CreateShortCut $SMPROGRAMS$STARTMENU_FOLDERLire la lissence gpl 3 en français.lnk $INSTDIRGPL-3.0.fr.html
  CreateShortCut $SMPROGRAMS$STARTMENU_FOLDERUniversal Reloader.lnk $INSTDIRUniversalReloader.exe
  CreateShortCut $SMPROGRAMS$STARTMENU_FOLDER$(^UninstallCaption).lnk $INSTDIRUninstall.exe
  SetShellVarContext current

  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd


# -------------------------------------------------------------------
# Desktop Section
# -------------------------------------------------------------------

Section
  SetShellVarContext all
  CreateShortCut $DESKTOPUniversal Reloader.lnk $INSTDIRUniversalReloader.exe
  SetShellVarContext current
SectionEnd


# -------------------------------------------------------------------
# Registry Section
# -------------------------------------------------------------------

Section
  WriteRegStr HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID}  ${SFX_Title}
  WriteRegStr HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID} InstallDirectory $INSTDIR
SectionEnd


# -------------------------------------------------------------------
# Initialization Functions
# -------------------------------------------------------------------

Function .onInit
  InitPluginsDir

  ClearErrors
  UserInfoGetName
  IfErrors RunTheInstaller
  Pop $0
  UserInfoGetAccountType
  Pop $1

  StrCmp $1 Admin RunTheInstaller
  StrCmp $1 Power RunTheInstaller
  MessageBox MB_OKMB_ICONSTOPMB_TOPMOST The user $$0$ is not allowed to install this application.$nPlease ask your administrator's permission !!!
  Quit

  RunTheInstaller
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Function InitializeGUI
  BGImageSetBG NOUNLOAD GRADIENT 0x00 0x00 0x80 0xA6 0xCA 0xF0
  CreateFont $R0 Verdana 22 700
  BGImageAddText NOUNLOAD $(^SetupCaption) $R0 0xFF 0xFB 0xF0 10 10 -10 -10
  BGImageRedraw NOUNLOAD
FunctionEnd

Function .onGUIEnd
  BGImageDestroy
FunctionEnd



# -------------------------------------------------------------------
# Uninstaller Section
# -------------------------------------------------------------------

Section Uninstall
  RMDir r $INSTDIR

  !insertmacro MUI_STARTMENU_GETFOLDER Application $R0
  SetShellVarContext all
  RMDir r $SMPROGRAMS$R0
  SetShellVarContext current

  SetShellVarContext all
  Delete $DESKTOPUniversal Reloader.lnk
  SetShellVarContext current

  DeleteRegKey HKLM SoftwareMicrosoftWindowsCurrentVersionUninstall${SFX_AppID}
SectionEnd


# -------------------------------------------------------------------
# Uninstaller Initialization Function
# -------------------------------------------------------------------

Function un.onInit
  InitPluginsDir

  ClearErrors
  UserInfoGetName
  IfErrors RunTheUninstaller
  Pop $0
  UserInfoGetAccountType
  Pop $1

  StrCmp $1 Admin RunTheUninstaller
  StrCmp $1 Power RunTheUninstaller
  MessageBox MB_OKMB_ICONSTOPMB_TOPMOST The user $$0$ is not allowed to uninstall this application.$nPlease ask your administrator's permission !!!
  Quit

  RunTheUninstaller
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Function un.InitializeGUI
  BGImageSetBG NOUNLOAD GRADIENT 0x00 0x00 0x80 0xA6 0xCA 0xF0
  CreateFont $R0 Verdana 22 700
  BGImageAddText NOUNLOAD $(^SetupCaption) $R0 0xFF 0xFB 0xF0 10 10 -10 -10
  BGImageRedraw NOUNLOAD
FunctionEnd

Function un.onGUIEnd
  BGImageDestroy
FunctionEnd



# ===================================================================
# End of File
# ===================================================================
